DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS album;
DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS playlist;
DROP TABLE IF EXISTS track;


CREATE TABLE users (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(30) NOT NULL,
    passcode VARCHAR(15) NOT NULL,
    username VARCHAR(15) NOT NULL
);

CREATE TABLE album (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    cover_art INTEGER NOT NULL,
    image_path INTEGER NOT NULL
);

CREATE TABLE account (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    playlist VARCHAR(20) NOT NULL,
    image_path INTEGER,
    CONSTRAINT fk_image
        FOREIGN KEY (image_path)
        REFERENCES album(id)
        ON DELETE SET NULL
);

CREATE TABLE playlist (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    track_name VARCHAR(30) NOT NULL
);

CREATE TABLE track (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    track_name VARCHAR(30) NOT NULL,
    track_link TEXT NOT NULL
);
