DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(30) NOT NULL,
    passcode VARCHAR(15) NOT NULL,
    username VARCHAR(15) NOT NULL
);

CREATE TABLE account (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    playlist VARCHAR(10) NOT NULL
);

CREATE TABLE playlist (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    track_name VARCHAR(20) NOT NULL,
    cover_art INTEGER,
);

CREATE TABLE track (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    track_name VARCHAR(20) NOT NULL,
    track_link NOT NULL,
);

CREATE TABLE album (
    id INTEGER AUTO_INCREMENT PRIMARY,
    image_id INTEGER NOT NULL,
    image_path NOT NULL
);